"""Registry of known-safe macOS cleanup targets.

This whitelist is the ONLY way locations enter the system. Everything
here is user-scope (inside $HOME), auto-regenerated by the app or tool
that owns it, and never contains user documents or app settings.

Deliberately excluded:
  * /System, /Library, /private/var/folders  -> macOS manages these itself
  * ~/Library/Application Support            -> app data & settings
  * ~/Library/Preferences, Containers        -> app settings/sandboxed data
  * ~/Downloads, ~/Documents, ~/Desktop      -> user files
"""
from __future__ import annotations

from pathlib import Path

from ..domain.entities import CleanupTarget, Risk

HOME = Path.home()


def default_targets() -> list[CleanupTarget]:
    return [
        CleanupTarget(
            id="user-caches",
            name="User app caches",
            description="Per-app cache folders in ~/Library/Caches. "
                        "Apps rebuild these automatically.",
            root=HOME / "Library" / "Caches",
            risk=Risk.SAFE,
            min_age_days=7,
        ),
        CleanupTarget(
            id="user-logs",
            name="User app logs",
            description="Old log files in ~/Library/Logs.",
            root=HOME / "Library" / "Logs",
            risk=Risk.SAFE,
            min_age_days=14,
        ),
        CleanupTarget(
            id="xcode-derived-data",
            name="Xcode DerivedData",
            description="Build intermediates; Xcode regenerates on next build.",
            root=HOME / "Library" / "Developer" / "Xcode" / "DerivedData",
            risk=Risk.SAFE,
            min_age_days=3,
        ),
        CleanupTarget(
            id="xcode-archives",
            name="Xcode old device support",
            description="iOS DeviceSupport symbol caches for old OS versions; "
                        "re-downloaded from a connected device when needed.",
            root=HOME / "Library" / "Developer" / "Xcode" / "iOS DeviceSupport",
            risk=Risk.MODERATE,
            min_age_days=60,
        ),
        CleanupTarget(
            id="homebrew-cache",
            name="Homebrew download cache",
            description="Downloaded bottles/formulae in ~/Library/Caches/Homebrew.",
            root=HOME / "Library" / "Caches" / "Homebrew",
            risk=Risk.SAFE,
            min_age_days=7,
        ),
        CleanupTarget(
            id="npm-cache",
            name="npm cache",
            description="~/.npm content-addressable cache; re-fetched on install.",
            root=HOME / ".npm" / "_cacache",
            risk=Risk.SAFE,
            min_age_days=14,
        ),
        CleanupTarget(
            id="yarn-cache",
            name="Yarn cache",
            description="Yarn package cache; re-fetched on install.",
            root=HOME / "Library" / "Caches" / "Yarn",
            risk=Risk.SAFE,
            min_age_days=14,
        ),
        CleanupTarget(
            id="pip-cache",
            name="pip cache",
            description="Python wheel/http cache; re-downloaded when needed.",
            root=HOME / "Library" / "Caches" / "pip",
            risk=Risk.SAFE,
            min_age_days=14,
        ),
        CleanupTarget(
            id="trash",
            name="Trash (older items)",
            description="Items already in your Trash. OPT-IN because emptying "
                        "Trash is permanent. Only items older than 30 days.",
            root=HOME / ".Trash",
            risk=Risk.OPT_IN,
            min_age_days=30,
        ),
    ]


def targets_by_id() -> dict[str, CleanupTarget]:
    return {t.id: t for t in default_targets()}
